server:
  port: 8081

everton:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
  cloud:
    openfeign:
      clients:
        address:
          url: ${everton.client.address.url}
          connect-timeout: 5000
          read-timeout: 5000
          logger-level: full
          micrometer.enabled: false